### ISSUE TITLE
Establish a better branch model

### ISSUE THREAD

**Issue by ambiso** [Ziddykins/Dawn#4]
Master should not contain buggy versions but only full releases. dev should be the main branch that is committed to. 
when adding a feature, create a feature branch and merge back into dev.

**Comment by ambiso** [comment]
welp can't assign 2 people to 1 issue

**Comment by Ziddykins** [comment]
Testing should be done prior to pushing anyway, I don't think we've ever used dev past the first month.

**Comment by ambiso** [comment]
Well we should
